application:
  host: "127.0.0.1"
  port: 8000
  hmac_secret: "long-and-super-secret-random-key"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "fatum"
  